Gd 190
IT-Siberians/NotificationMicroservice pull request #13
Opened 2024-10-01 01:39 UTC by Barmalej24

Уровень домена
1. Реализован абстрактный класс StringValueObject
2. StringValueObject унаследован всем ValueObject
3. Добавлена новая сущность для работы с именами очередей (соотношение очереди с типом шаблона уведомления)
4. Во всех сущностях максимально используются реализованные ValueObject
5. Добавлен enum для языка шаблона
6. Удален enum для событий

Уровень Data
1. Реализован базовый абстрактный репозиторий
2. Реализован интерфейс репозитория для новой доменной сущности очередей
3. Реализован репозиторий для новой доменной сущности очередей
4. Внесены изменения (добавлено наследование базового репозитория) во все ранее существовавшие репозитории сущностей
5. Добавлена конфигурация EF для новой доменной сущности

Уровень приложения
1. Добавлен маркерный интерфейс для моделей создания
2. Во все интерфейсы сервисов и реализации сервисов добавлены токены отмены
3. Добавлен интерфейс для сервиса работы с новой доменной сущностью
4. Реализован сервис по работе с новой доменной сущностью
5. Добавлены новые модели для работы с новой доменной сущностью

Уровень представления
1. Добавлен сервис для отправки сообщений в очереди (в сторону Email сервиса)
2. Добавлен сервис принятия сообщений из очереди от сервисов Регистрации и Профиля пользователя
3. Добавлен котроллер для работы с новой доменной сущностью 
4. Добавлены контракты для новой доменной сущности
5. Изменен валидатор для языка шаблона

2024-10-01 12:41 UTC, oleggolen requested changes
Тут у меня промелькнула идея переписать это всё дело вообще на чистую архитектуру, потому что мне очень не нравятся классы, в которых упомянаются ифраструктурные вещи типа очереди сообщений в домене, ну вот вообще они не имеют никакого отношения к предметной области решаемой задачи, а так будут эти классы только в инфраструктуре, и репозитории для работы с ними будут там же и никакой домент и бизнес-логика не будут знать ничего про то, что там по брокерам гоняется, как собственно и должно быть. Также ещё несколько моментов по аккуратности кода и контейнеризации., ну и поубирать лишние контроллеры,  и для низ DTO лучше это всё сразу через брокер тестировать. Кстати брокер я бы тоже внёс бы в docker-compose файл, на него бы навесил переменные и health checks. В общем надо подумать, как лучше сделать, но у меня соображения такие

2024-10-01 12:41 UTC, oleggolen commented on docker-compose.yml
> +
необходимо добавить health checks для базы данных

2024-10-01 12:41 UTC, oleggolen commented on docker-compose.yml
> +      - db
данные подключения к базе данных лучше передавать в контейнер бэкэнда переменными окружения

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Domain/Entities/MessageTemplate.cs
> +        public const int TEMPLATE_MAX_LENGTH = 600;
Я бы не ограничивал длину шаблона сообщения

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.DataAccess/Configuration/TemplateConfiguration.cs
>                  .IsRequired();
Я бы не ограничевал длину шаблона сообщения

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.DataAccess/Configuration/MessageConfiguration.cs
> +                    s => new MessageText(s))
Я бы не ограничевал длину сообщения

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Services/MessageTemplateService.cs
> +                return null;
Я бы здесь не возвращал null, а вернул бы пустую коллекцию, да и условие никогда не выполнится, так как из оепозитория возвращается тоже пустая коллекция, а не nullable тип

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Model/User/UserModel.cs
>      {
Лучше просто все поля сделать required или хотя бы некоторые, такие как UserName и Email они гарантированно должны приходить

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Type/UpdateTypeModel.cs
>      {
Лучше сделать всё required

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Type/TypeModel.cs
Лучше сделать все свойства required

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Type/DeleteTypeModel.cs
Все свойства сделать required

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Template/UpdateTemplateModel.cs
Лучше все поля сделать required

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Template/TemplateModel.cs
Лучше все поля сделать required кроме nullable

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Template/DeleteTemplateModel.cs
Лучше все поля сделать required

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Model/BusQueue/UpdateBusQueueModel.cs
Лучше все поля сделать required

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Model/BusQueue/DeleteBusQueueModel.cs
Лучше все поля сделать required

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Abstractions/IBaseModel.cs
>      public interface IBaseModel<Tkey> where Tkey : struct
Добавить ещё, что ключи сравниваемые

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Validator/Queue/EditBusQueueValidator.cs
> +        }
Лишний класс

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Validator/Queue/DeleteBusQueueValidator.cs
> +    }
Лишний класс

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Validator/Queue/AddBusQueueValidator.cs
> +        }
Лишний класс

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Controllers/BusQueueController.cs
> +}
Лишний контроллер

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Validator/Base/QueueNameValidator.cs
> +    }
Лишний класс

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Validator/Event/UpdateUserValidator.cs
> +        }
Лишний класс

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Validator/Event/CreateUserValidator.cs
> +        }
Лишний класс

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Validator/Event/ConfirmationEmailValidator.cs
> +    }
Лишний класс

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Services/NotificationControlService.cs
> +            return false;
Как будто бы здесь лучше всего использовать паттерн команда и фабричный метод для этих команд, потому что так выглядит очень сильно, либо использовать фабричный метод и MediatR

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Services/NotificationControlService.cs
> +        }
Вот тут можно попробовать в репозиториях идею с IQuerible или дописать репозиторию конкретный метод с выборкой по языку и типу сообщения, чтобы не писать вот такие килмометровые портянки выборки из БД на уровне приложения

2024-10-01 12:41 UTC, oleggolen commented on NotificationMicroservice/Contracts/BusQueue/DeleteBusQueueRequest.cs
> +    public record DeleteBusQueueRequest(Guid ModifiedByUserId);
Лишний класс

2024-10-01 14:16 UTC, Barmalej24 commented on NotificationMicroservice.DataAccess/Configuration/MessageConfiguration.cs
> +                    s => new MessageText(s))
сообщение не ограничено по длине

2024-10-01 14:16 UTC, Barmalej24 commented on NotificationMicroservice.DataAccess/Configuration/TemplateConfiguration.cs
>                  .IsRequired();
убрал.

2024-10-01 14:16 UTC, Barmalej24 commented on NotificationMicroservice.Domain/Entities/MessageTemplate.cs
> +        public const int TEMPLATE_MAX_LENGTH = 600;
убрал

2024-10-01 14:16 UTC, Barmalej24 commented on docker-compose.yml
> +
добавил

2024-10-01 14:22 UTC, Barmalej24 commented on NotificationMicroservice.Application/Model/User/UserModel.cs
>      {
преобразовал в запись

2024-10-01 14:29 UTC, Barmalej24 commented on NotificationMicroservice.Application/Model/Type/TypeModel.cs
преобразовал в запись

2024-10-01 14:29 UTC, Barmalej24 commented on NotificationMicroservice.Application/Model/Template/TemplateModel.cs
преобразовал в запись

2024-10-01 14:33 UTC, Barmalej24 commented on NotificationMicroservice.Application/Model/Abstractions/IBaseModel.cs
>      public interface IBaseModel<Tkey> where Tkey : struct
добавил

2024-10-01 14:37 UTC, Barmalej24 commented on NotificationMicroservice.Application/Model/BusQueue/DeleteBusQueueModel.cs
добавил

2024-10-01 14:37 UTC, Barmalej24 commented on NotificationMicroservice.Application/Model/BusQueue/UpdateBusQueueModel.cs
добавил

2024-10-01 14:37 UTC, Barmalej24 commented on NotificationMicroservice.Application/Model/Template/DeleteTemplateModel.cs
добавил

2024-10-01 14:37 UTC, Barmalej24 commented on NotificationMicroservice.Application/Model/Template/UpdateTemplateModel.cs
добавил

2024-10-01 14:37 UTC, Barmalej24 commented on NotificationMicroservice.Application/Model/Type/DeleteTypeModel.cs
добавил

2024-10-01 14:37 UTC, Barmalej24 commented on NotificationMicroservice.Application/Model/Type/UpdateTypeModel.cs
>      {
добавил

2024-10-01 14:40 UTC, Barmalej24 commented on NotificationMicroservice/Validator/Event/ConfirmationEmailValidator.cs
> +    }
удалил.

2024-10-01 14:40 UTC, Barmalej24 commented on NotificationMicroservice/Validator/Event/CreateUserValidator.cs
> +        }
удалил.

2024-10-01 14:40 UTC, Barmalej24 commented on NotificationMicroservice/Validator/Event/UpdateUserValidator.cs
> +        }
удалил.

2024-10-01 15:13 UTC, Barmalej24 commented on NotificationMicroservice/Services/NotificationControlService.cs
> +        }
вынес в репозиторий

2024-10-02 13:02 UTC, Barmalej24 commented on NotificationMicroservice.Application/Services/MessageTemplateService.cs
> +                return null;
убрал

2024-10-02 13:54 UTC, closed without merging