Gd 121
IT-Siberians/NotificationMicroservice pull request #6
Opened 2024-08-24 04:16 UTC by Barmalej24

2024-08-26 17:34 UTC, oleggolen approved these changes
В целом достаточно непоохой и работчий код, вс

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Contracts/Template/TemplateDeleteRequest.cs
> +    public record TemplateDeleteRequest(string ModifiedUserName);
Почему бы не использовать Id пользователя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Contracts/Type/TypeAddRequest.cs
> +        string CreatedUserName
Почему бы не использовать Id пользователя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Contracts/Type/TypeDeleteRequest.cs
> +    public record TypeDeleteRequest(string ModifiedUserName);
Почему не использовать Id пользователя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Contracts/Template/TemplateAddRequest.cs
> +        string CreatedUserName
Почему не использовать Id пользователя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Contracts/Type/TypeEditRequest.cs
> +        string ModifiedUserName
Почему не использовать Id пользователя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Contracts/Type/TypeResponse.cs
> +        string CreatedUserName,
Почему не использовать Id пользователя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Contracts/Type/TypeResponse.cs
> +        string? ModifiedUserName,
Почему не использовать Id пользователя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Program.cs
> +                    options.UseNpgsql(builder.Configuration.GetConnectionString(nameof(NotificationMicroserviceDbContext)));
Добавить проверку строки подключения на null

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Program.cs
> +
Можно добавить все валидаторы FluentValidation одной командой и не таскать их через DI

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Controllers/MessageTemplateController.cs
> +            var result = validator.Validate(request);
Убрать в конфигурацию Program

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Controllers/MessageTemplateController.cs
> +            }
Не нужна проверка, если написать в Program добавление middleware FluentValidation

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Controllers/MessageTemplateController.cs
> +            }
Убрать в соответствующую Middleware

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Controllers/MessageTemplateController.cs
> +            };
Использовать AutoMapper

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Controllers/MessageTemplateController.cs
> +            };
Использовать библиотеки FlunentValidation и AutoMapper

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Controllers/MessageTypeController.cs
> +            }
Перетащить в соответствующую Middleware

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Controllers/MessageTypeController.cs
> +
Перетащить в соответствующую Middleware и использовать Automapper

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice/Controllers/MessageTypeController.cs
> +            };
Перетащить в соответствующую Middleware и использовать AutoMapper

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Message/MessageModel.cs
> +        public string Direction { get; init; }
Использовать required

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Template/CreateTemplateModel.cs
> +        string CreatedUserName
Почему не Id пользователя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Template/EditTemplateModel.cs
> +        public string ModifiedUserName { get; init; }
Почему не Iв пользоателя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Template/EditTemplateModel.cs
> +        public string Template { get; init; }
Использовать required

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Template/TemplateModel.cs
> +        public string Template { get; init; }
Ипользовать required

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Template/TemplateModel.cs
> +        public string CreatedUserName { get; init; }
Использовать required

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Type/CreateTypeModel.cs
> +        public string CreatedUserName { get; init; }
Почему не Id пользователя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Type/CreateTypeModel.cs
> +        public string Name { get; init; }
Использовать required

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Type/EditTypeModel.cs
> +        public string Name { get; init; }
Использовать required

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Type/EditTypeModel.cs
> +        public string ModifiedUserName { get; init; }
Почему не Id пользователя?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Model/Type/TypeModel.cs
> +        public bool IsRemoved { get; init; }
Использовать required

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Services/MessageTemplateService.cs
> +            var template = new MessageTemplate(Guid.NewGuid(), type, messageTemplate.Language, messageTemplate.Template, false, messageTemplate.CreatedUserName, DateTime.UtcNow, null, null);
Почему не доверить генерацию Id базе данных?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Application/Services/MessageTypeService.cs
> +            var typeNew = new MessageType(Guid.NewGuid(), type.Name, false, type.CreatedUserName, DateTime.UtcNow, null, null);
Почему не доверить генерацию Id базе данных?

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Domain/Exception/MessageType/MessageTypeGuidEmptyException.cs
> +    public class MessageTypeGuidEmptyException(string message, string value) : ArgumentException(message, value)
Использовать ArgumentNullException

2024-08-26 17:34 UTC, oleggolen commented on NotificationMicroservice.Domain/Exception/Message/MessageGuidEmptyException.cs
> +    public class MessageGuidEmptyException(string message, string value) : ArgumentException(message, value)
Использовать ArgumentNullException

2024-08-26 17:36 UTC, oleggolen requested changes
В целом достаточно неплохой рабочий код, всё работает, написаны слои, выделена архитектура, всё число. Единственное стоит на уровне представлений больше перенести на уровень Middleware и сделать констроллеры более маленькими, а также для фронта и других сервисов будет удобнее передавать Id пользователя и информацию о них, поэтому это можно будет хранить отдельно в базе данных, и если там надо будет для визуала показывать имена, но не держать это как уникальными идентификаторами пользователей

2024-08-27 19:53 UTC, m-a-ilnitsky approved these changes
Есть мелкие замечания.
Видно, что не исправлены многие прошлые замечания по именам свойств/классов/папок.
И я всё-таки по прежнему считаю, что неправильно в исключениях сохранять значение  аргумента в поле предназначенное для имени аргумента.
Но лучше уже всё это вмёрджить в dev, а исправлять в fix-ветках

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Application/Services/MessageTemplateService.cs
> +            var template = new MessageTemplate(Guid.NewGuid(), type, messageTemplate.Language, messageTemplate.Template, false, messageTemplate.CreatedUserName, DateTime.UtcNow, null, null);
А у него в конструкторе MessageTemplate сделана проверка на равенство Id значению Guid.Empty.
Т.е. в этом случае будет брошено исключение.
С такой проверкой не удастся переложить это на БД

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Application/Services/MessageTemplateService.cs
> +            template.Update(type, messageTemplate.Language, messageTemplate.Template, messageTemplate.IsRemoved, messageTemplate.ModifiedUserName, DateTime.UtcNow);
Для этого метода Update логичнее сделать, чтобы он просто принимал объект messageTemplate и сам из него доставал все нужные параметры (может даже параметр type, если он хранится в template и не должен меняться, но здесь вам виднее как правильнее).
А текущее время метод Update может получить сам, если это время обновления, то там всегда должно быть текущее время, тогда не нужен лишний аргумент

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Application/Services/MessageTemplateService.cs
> +            template.Delete(messageTemplate.ModifiedUserName, DateTime.UtcNow);
Здесь скорее всего тоже не нужно передавать текущее время параметром, а получить в самом методе Delete.
Т.к. вряд ли там нужно передавать какое-то другое время отличное от текущего

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Application/Services/MessageTemplateService.cs
> +            template.Delete(messageTemplate.ModifiedUserName, DateTime.UtcNow);
И думаю этот метод логичнее вызывать в методе DeleteAsync репозитория.
Правда тогда нужно будет передавать в DeleteAsync информацию о том кто удаляет.
Сейчас получается, что метод DeleteAsync в репозитории сам по себе не реализует логику удаления

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Application/Services/MessageTypeService.cs
> +            var typeNew = new MessageType(Guid.NewGuid(), type.Name, false, type.CreatedUserName, DateTime.UtcNow, null, null);
Здесь тоже для Guid.Empty будет брошено исключение, поэтому в текущей логике можно только так.
Можно конечно добавить конструктор не принимающий Id.
Но если Id является Guid-ом то непонятно зачем перекладывать его генерацию на БД.
Вот если делать в общем виде, чтобы можно было использовать как Guid, так и int, то конечно эта проверка добавляет головняк

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.DataAccess/NotificationMicroserviceDbContext.cs
> +        public DbSet<MessageTemplate> Templates { get; set; }
Поля и свойства лучше объявлять выше конструкторов и методов.
Здесь это не влияет на читаемость, но когда все сделано единообразно, код читать существенно легче

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Domain/Exception/Helpers/ExceptionString.cs
> +    public static class ExceptionString
Здесь классу лучше дать имя во множественном числе: ExceptionStrings
Но думаю лучше назвать ExceptionMessages

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Domain/Exception/Helpers/ExceptionString.cs
> +﻿namespace NotificationMicroservice.Domain.Exception.Helpers
Имя namespace не подходит по смыслу.
Лучше namespace и папку назвать, например, Strings или Constants

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Domain/Exception/Message/MessageDirectionNullOrEmptyException.cs
> +    public class MessageDirectionNullOrEmptyException(string message, string value) : ArgumentNullException(value, message)
Лучше не смешивать null и пустую строку в одном исключении, т.к. у них как правило разные причины.
Т.к. исключение унаследовано от ArgumentNullException здесь лучше оставить только случай null

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Domain/Exception/Message/MessageGuidEmptyException.cs
> +    public class MessageGuidEmptyException(string message, string value) : ArgumentException(message, value)
Здесь не согласен, т.к. это исключение не связано с null.
Здесь ArgumentException вполне уместно смотрится

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Domain/Exception/Message/MessageDirectionNullOrEmptyException.cs
> +    public class MessageDirectionNullOrEmptyException(string message, string value) : ArgumentNullException(value, message)
Или если хочется объять эти случаи одним исключением, то лучше наследоваться не от ArgumentNullException, а от его родителя ArgumentException

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Domain/Exception/Message/MessageDirectionNullOrEmptyException.cs
> +    public class MessageDirectionNullOrEmptyException(string message, string value) : ArgumentNullException(value, message)
Впрочем, если в ветвлениях смешивать смешивать null и пустую строку вполне уместно (для чего и сделан string.IsNullOrWhiteSpace()).
В исключениях лучше их раздельно рассматривать, чтобы по исключению было однозначно понятно какой из вариантов реализовался.
Я не что здесь можно будет в сообщении различить пустую строку и null в качестве значения, указанного вместо имени параметра

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Domain/Exception/MessageTemplate/MessageTemplateLanguageNullOrEmptyException.cs
> +    public class MessageTemplateLanguageNullOrEmptyException(string message) : ArgumentNullException(message)
Аналогично про null и пустую строку, и ArgumentNullException

2024-08-27 19:53 UTC, m-a-ilnitsky commented on NotificationMicroservice.Domain/Exception/MessageTemplate/MessageTemplateNullOrEmptyException.cs
> +    public class MessageTemplateNullOrEmptyException(string message, string value) : ArgumentNullException(value, message)
Аналогично про null и пустую строку, и ArgumentNullException

2024-08-29 13:45 UTC, closed without merging